### ISSUE TITLE
Error while using yala.

### ISSUE THREAD

**Issue by diraol** [cemsbr/yala#18]
```python
Traceback (most recent call last):
  File "/home/.../.virtualenvs/kytos/bin/yala", line 7, in <module>
    from yala.main import main
  File "/home/.../.virtualenvs/kytos/lib/python3.6/site-packages/yala/__init__.py", line 6, in <module>
    disable_existing_loggers=False)
  File "/usr/local/lib/python3.6/logging/config.py", line 74, in fileConfig
    cp.read(fname)
  File "/usr/local/lib/python3.6/configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'PosixPath' object is not iterable
```

**Comment by cemsbr** [comment]
I couldn't reproduce it, but I believe it's due to Python bpo-29623. If so, it should be fixed now. Please, reopen with your Python version if are you still having problems.

**Comment by diraol** [comment]
The versions that raised errors were:
`Python`: 3.6.0
`yala`: 1.3.0

I've updated `yala` and now it is working. ;)
